# Generated by Django 5.0.1 on 2024-02-08 16:43

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('full_transcription', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('paragraphs', models.JSONField(blank=True, null=True)),
                ('words', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClipParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.FloatField(blank=True, null=True)),
                ('start', models.FloatField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('sentences', models.JSONField(blank=True, null=True)),
                ('full_transcription', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.clip')),
            ],
        ),
    ]
