# Generated by Django 5.0.1 on 2024-02-08 16:51

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipparagraph',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
