# Generated by Django 5.0.1 on 2024-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_alter_clipparagraph_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
