# Generated by Django 4.2.10 on 2024-02-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_rename_clip_id_chapters_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start', models.FloatField(blank=True, null=True)),
                ('paragraphs', models.JSONField(blank=True, null=True)),
                ('chapter_transcription', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.clip')),
            ],
        ),
        migrations.DeleteModel(
            name='Chapters',
        ),
    ]
